import inspect
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

import numpy as np
import torch
from transformers import AutoConfig, AutoTokenizer

from gena_lm.utils import get_cls_by_name

service_folder = Path(__file__).parent.absolute()


@dataclass
class DeepSeaConf:
    working_segment = 1000
    segment_step = 200
    batch_size = 8
    max_seq_len = 1000
    target_len = 200
    context_len = 400
    max_tokens = 256
    num_labels = 919
    tokenizer = service_folder.joinpath('data/tokenizers/human/BPE_32k/')
    model_cls = 'gena_lm.modeling_bert:BertForSequenceClassification'
    model_cfg = service_folder.joinpath('data/configs/L12-H768-A12-V32k-preln.json')
    checkpoint_path = service_folder.joinpath('data/checkpoints/model_best.pth')


class DeepSeaService:
    def __init__(self, config: dataclass):
        self.conf = config

        # define tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(config.tokenizer)

        # define model | multi-class sequence classification
        model_cfg = AutoConfig.from_pretrained(config.model_cfg)
        model_cfg.num_labels = config.num_labels
        model_cfg.problem_type = 'multi_label_classification'
        model_cls = get_cls_by_name(config.model_cls)
        self.model = model_cls(config=model_cfg)
        checkpoint = torch.load(config.checkpoint_path, map_location=torch.device('cpu'))
        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.model.eval()
        self.model_forward_args = set(inspect.getfullargspec(self.model.forward).args)

    @staticmethod
    def dna_string_padding(seq: str, length: int):
        pad_len = (length - len(seq)) // 2
        seq = ('N' * pad_len) + seq + ('N' * pad_len)
        if len(seq) < length:
            seq += 'N' * (length - len(seq))

        return seq

    def preprocess(self, dna_seq: str):
        features = self.tokenizer(dna_seq,
                                  add_special_tokens=True,
                                  padding='max_length',
                                  truncation='longest_first',
                                  max_length=self.conf.max_tokens,
                                  return_tensors='np')
        # return features generated by tokenizer and labels
        for fn in features:
            features[fn] = features[fn][0]

        return features

    @staticmethod
    def create_batch(seq_list: List[Dict]) -> Dict:
        batch = {'input_ids': [],
                 'token_type_ids': [],
                 'attention_mask': [],
                 'labels': None,
                 "labels_ohe": None,
                 'labels_mask': None}

        for features in seq_list:
            batch['input_ids'].append(features['input_ids'])
            batch['token_type_ids'].append(features['token_type_ids'])
            batch['attention_mask'].append(features['attention_mask'])

        batch['input_ids'] = torch.from_numpy(np.vstack(batch['input_ids'])).int()
        batch['token_type_ids'] = torch.from_numpy(np.vstack(batch['token_type_ids'])).int()
        batch['attention_mask'] = torch.from_numpy(np.vstack(batch['attention_mask'])).float()

        return batch

    def __call__(self, dna_examples: List[str]) -> Dict:
        # preprocessing
        batch = []
        for dna_seq in dna_examples:
            batch.append(self.preprocess(dna_seq))

        # model inference
        batch = self.create_batch(batch)
        model_out = self.model(**{k: batch[k] for k in batch if k in self.model_forward_args})

        # postprocessing
        service_response = dict()
        # write predictions
        predictions = torch.sigmoid(model_out['logits']).detach().numpy()
        labels = np.where(predictions > 0.5, 1, 0)
        service_response['prediction'] = labels  # [bs, 919]
        # write tokens
        service_response['seq'] = []
        input_ids = batch['input_ids'].detach().numpy()
        for batch_element in input_ids:
            service_response['seq'].append(self.tokenizer.convert_ids_to_tokens(batch_element,
                                                                                skip_special_tokens=True))

        return service_response
